import datetime
import logging
from decimal import Decimal
from unittest import TestCase

import pytz

from foxylib.tools.collections.dicttree.dicttree_tool import DicttreeTool
from foxylib.tools.log.foxylib_logger import FoxylibLogger


class TestDicttreeTool(TestCase):
    @classmethod
    def setUpClass(cls):
        FoxylibLogger.attach_stderr2loggers(logging.DEBUG)

    def test_01(self):
        class A: pass

        data_in = {'body': {
            'next_render_at': datetime.datetime(2021, 1, 9, 1, 26, 5, 958000,
                                                tzinfo=pytz.utc),
            'program': {'_id': '5ff90621ad5fa0db25cf0642',
                        'chatstreammarks':[{
                            'chatstream_key': 'youtube/Cg0KC2VQbldCSm5qN0MwKicKGFVDTDI5X1pkaENHV3pjMTZ1NW04S19VURILZVBuV0JKbmo3QzA'}],
                        'bufflevels': [{'background_color': '#000000',
                                        'color': 'white',
                                        'interval': [{'inex': False,
                                                      'value': None},
                                                     {'inex': True,
                                                      'value': -10000}],
                                        'rate': '-0.5',
                                        'stroke_color': 'rgba(0, 0, 0, 0.7)'},
                                       {'background_color': '#000000',
                                        'color': 'white',
                                        'interval': [{'inex': False,
                                                      'value': -10000},
                                                     {'inex': True,
                                                      'value': -1000}],
                                        'rate': '-0.4',
                                        'stroke_color': 'rgba(0, 0, 0, 0.7)'},
                                       {'background_color': '#000000',
                                        'color': 'white',
                                        'interval': [{'inex': False,
                                                      'value': -1000},
                                                     {'inex': True,
                                                      'value': -100}],
                                        'rate': '-0.3',
                                        'stroke_color': 'rgba(0, 0, 0, 0.7)'},
                                       {'background_color': '#000000',
                                        'color': 'white',
                                        'interval': [{'inex': False,
                                                      'value': -100},
                                                     {'inex': True,
                                                      'value': -10}],
                                        'rate': '-0.2',
                                        'stroke_color': 'rgba(0, 0, 0, 0.7)'},
                                       {'background_color': '#7c7c7c',
                                        'color': 'white',
                                        'interval': [{'inex': False,
                                                      'value': -10},
                                                     {'inex': True,
                                                      'value': -1}],
                                        'rate': '-0.1',
                                        'stroke_color': 'rgba(0, 0, 0, 0.7)'},
                                       {'background_color': '#cccccc',
                                        'color': 'black',
                                        'interval': [
                                            {'inex': False, 'value': -1},
                                            {'inex': False, 'value': 0}],
                                        'rate': '0'},
                                       {'background_color': '#cccccc',
                                        'color': 'black',
                                        'interval': [{'inex': True, 'value': 0},
                                                     {'inex': False,
                                                      'value': 1}],
                                        'rate': '0'},
                                       {'background_color': '#fd4646',
                                        'color': 'black',
                                        'interval': [{'inex': True, 'value': 1},
                                                     {'inex': False,
                                                      'value': 10}],
                                        'rate': '0.1'},
                                       {'background_color': '#ffb307',
                                        'color': 'black',
                                        'interval': [
                                            {'inex': True, 'value': 10},
                                            {'inex': False,
                                             'value': 100}],
                                        'rate': '0.2'},
                                       {'background_color': '#2de4c0',
                                        'color': 'black',
                                        'interval': [
                                            {'inex': True, 'value': 100},
                                            {'inex': False,
                                             'value': 1000}],
                                        'rate': '0.3'},
                                       {'background_color': '#0074c1',
                                        'color': 'black',
                                        'interval': [{'inex': True,
                                                      'value': 1000},
                                                     {'inex': False,
                                                      'value': 10000}],
                                        'rate': '0.4'},
                                       {'background_color': '#01a900',
                                        'color': 'black',
                                        'interval': [{'inex': True,
                                                      'value': 10000},
                                                     {'inex': False,
                                                      'value': None}],
                                        'rate': '0.5'}],
                        'channel_key': 'foxy_tv',
                        'created_at': datetime.datetime(2020, 7, 25, 5, 7, 39,
                                                        tzinfo=pytz.utc),
                        'description': 'hello world',
                        'ends_at': datetime.datetime(2021, 1, 9, 1, 56, 52,
                                                     958000,
                                                     tzinfo=pytz.utc),
                        'extra': {'_cache': {
                            'matcher': A()},
                            'choices': [{'aliases': [{'labels': ['name'],
                                                      'text': '방탄소년단'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅂㅌ'},
                                                     {'text': 'bts'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/n0wsqtM/BTS2-crop.jpg'}],
                                         'key': 'bts'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '빅뱅'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅂㅂ'},
                                                     {'text': 'bang'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/bXXz8Nd/bigbang5.jpg'}],
                                         'key': 'bang'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '엑소'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅇㅅ'},
                                                     {'text': 'exo'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/b7sZktB/Exo-8-crop.jpg'}],
                                         'key': 'exo'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': 'HOT'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '핫'},
                                                     {'text': 'hot'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/DkcxMSw/HOT.jpg'}],
                                         'key': 'hot'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '젝스키스'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅈㅋ'},
                                                     {'text': 'sk'}],
                                         'images': [{
                                             'url': 'https://i.ibb.co/Bnzq7sW/Sechskiess-crop.jpg'}],
                                         'key': 'sk'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': 'GOD'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅈㄷ'},
                                                     {'text': 'god'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/DKKSJS9/GOD.jpg'}],
                                         'key': 'god'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '워너원'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅇㄴㅇ'},
                                                     {'text': 'one'}],
                                         'images': [{
                                             'url': 'https://i.ibb.co/zJYznm1/Wanna-One4-crop.jpg'}],
                                         'key': 'one'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '신화'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅅㅎ'},
                                                     {'text': 'snh'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/ZgWvjyh/Shinhwa.jpg'}],
                                         'key': 'snh'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '구 동방신기'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㄷㅂ5'},
                                                     {'text': 'tv5'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/SmphD4y/TVQX-5member2.jpg'}],
                                         'key': 'tv5'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '슈퍼주니어'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅅㅈ'},
                                                     {'text': 'SJ'}],
                                         'images': [{
                                             'url': 'https://i.ibb.co/CVfSqfc/Super-Junior2-crop.jpg'}],
                                         'key': 'SJ'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '동방신기'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㄷㅂ'},
                                                     {'text': 'tv2'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/TP1dtwP/TVQX-2member.jpg'}],
                                         'key': 'tv2'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '투피엠'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '2pm'},
                                                     {'text': '2pm'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/yPMVmP7/2PM.jpg'}],
                                         'key': '2pm'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '샤이니'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '샤'},
                                                     {'text': 'shn'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/jVZTsJ2/SHINee-crop.jpg'}],
                                         'key': 'shn'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '하이라이트 '
                                                              '(비스트)'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '할'},
                                                     {'text': 'hl'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/MsSnv7x/Highlight.jpg'}],
                                         'key': 'hl'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '씨앤블루'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'cn'},
                                                     {'text': 'cn'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/d5rj2vw/CNblue.jpg'}],
                                         'key': 'cn'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': 'FT아일랜드'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ft'},
                                                     {'text': 'ft'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/614vSdq/FTisland.jpg'}],
                                         'key': 'ft'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '더블에스오공일'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ss'},
                                                     {'text': 'ss'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/B4wgBjX/SS501.jpg'}],
                                         'key': 'ss'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '인피니트'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅇㅍ'},
                                                     {'text': 'inf'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/98Nt6ZW/Infinite.jpg'}],
                                         'key': 'inf'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '위너'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅇㄴ'},
                                                     {'text': 'wnr'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/6wS0B33/Winner.jpg'}],
                                         'key': 'wnr'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '갓세븐'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '갓'},
                                                     {'text': 'g7'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/9hWp5JR/Godseven.jpg'}],
                                         'key': 'g7'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '세븐틴'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '17'},
                                                     {'text': '17'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/K2qbcyt/Seventeen.jpg'}],
                                         'key': '17'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': 'B1A4'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ba'},
                                                     {'text': 'b1'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/87zLXPN/B1A4.jpg'}],
                                         'key': 'b1'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '블락비'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '블'},
                                                     {'text': 'bb'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/LvTKhgW/BlockB.jpg'}],
                                         'key': 'bb'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '아이콘'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '콘'},
                                                     {'text': 'kon'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/ZhXWfCS/iKon.jpg'}],
                                         'key': 'kon'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': 'NCT'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'nct'},
                                                     {'text': 'nct'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/VjKnFkY/NCT.jpg'}],
                                         'key': 'nct'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '스트레이키즈'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅅㅋ'},
                                                     {'text': 'skz'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/WPXSvdK/Stray-Kids.jpg'}],
                                         'key': 'skz'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '뉴이스트'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '뉴'},
                                                     {'text': 'nu'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/x8b2Bzr/Newest.jpg'}],
                                         'key': 'nu'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '제국의 아이들'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅈㅇ'},
                                                     {'text': 'zea'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/gghZRdH/JeA.jpg'}],
                                         'key': 'zea'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '비투비'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': '투'},
                                                     {'text': 'btb'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/ys64Wvx/BtoB.jpg'}],
                                         'key': 'btb'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '몬스타엑스'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅁㅇ'},
                                                     {'text': 'mx'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/HYWhQCy/MonstaX.jpg'}],
                                         'key': 'mx'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '빅스'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'vx'},
                                                     {'text': 'vx'}],
                                         'images': [{
                                                        'url': 'https://i.ibb.co/HBWCxNY/Vixx.jpg'}],
                                         'key': 'vx'},
                                        {'aliases': [{'labels': ['name'],
                                                      'text': '펜타곤'},
                                                     {'labels': [
                                                         'hotkey_sample'],
                                                      'text': 'ㅍㅌ'},
                                                     {'text': 'pt'}],
                                         'images': [
                                             {
                                                 'url': 'https://i.ibb.co/286XZJG/Pentagon.jpg'}],
                                         'key': 'pt'}],
                            'detector': {'case': 'insensitive',
                                         'vote_types': ['vote', 'devote']},
                            'matches': [{'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 26,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'bang vs bts',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        25, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'bts',
                                                    'score': Decimal('1')},
                                                   {'choice_key': 'bang',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 27,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'exo vs hot',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        26, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'exo',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'hot',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 28,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'god vs sk',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        27, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'sk',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'god',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 29,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'one vs snh',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        28, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'one',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'snh',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 30,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'SJ vs tv5',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        29, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'tv5',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'SJ',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 31,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': '2pm vs tv2',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        30, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'tv2',
                                                    'score': Decimal('0')},
                                                   {'choice_key': '2pm',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 32,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'hl vs shn',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        31, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'shn',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'hl',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 33,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'cn vs ft',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        32, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'cn',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'ft',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 34,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'inf vs ss',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        33, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'ss',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'inf',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 35,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'g7 vs wnr',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        34, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'wnr',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'g7',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 36,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': '17 vs b1',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        35, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': '17',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'b1',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 37,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'bb vs kon',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        36, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'bb',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'kon',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 38,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'nct vs skz',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        37, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'nct',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'skz',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 39,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'nu vs zea',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        38, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'nu',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'zea',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 40,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'btb vs mx',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        39, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'btb',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'mx',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'},
                                        {'ends_at': datetime.datetime(2021, 1,
                                                                      9, 1, 41,
                                                                      52,
                                                                      958000,
                                                                      tzinfo=pytz.utc),
                                         'key': 'pt vs vx',
                                         'round': 32,
                                         'starts_at': datetime.datetime(2021, 1,
                                                                        9, 1,
                                                                        40, 52,
                                                                        958000,
                                                                        tzinfo=pytz.utc),
                                         'stats': [{'choice_key': 'vx',
                                                    'score': Decimal('0')},
                                                   {'choice_key': 'pt',
                                                    'score': Decimal('0')}],
                                         'title': 'round of 32'}],
                            'rounds': [{'durations': {'calculation': '2s',
                                                      'celebration': '5s',
                                                      'voting': '53s'},
                                        'size': 'default'}]},
                        'ingested_at': datetime.datetime(2021, 1, 9, 1, 25, 54,
                                                         682000,
                                                         tzinfo=pytz.utc),
                        'owner_key': 'foxytrixy',
                        'program_type': 'pollbattle/tourney',
                        'starts_at': datetime.datetime(2021, 1, 9, 1, 25, 52,
                                                       958000,
                                                       tzinfo=pytz.utc),
                        'tags': ['test', 'sample'],
                        'title': 'KPOP idol tournament',
                        'version': '1.0.0'},
            'votes': [{'_id': '5ff90623e19c1de6e6ab90c6',
                       # 'author_display': 'ptah-dev',
                       'author': {'key':'youtube/UCL29_ZdhCGWzc16u5m8K_UQ',
                                  'display':'ptah-dev',
                                  },
                       'chat_key': 'youtube/LCC.CjgKDQoLZVBuV0JKbmo3QzAqJwoYVUNMMjlfWmRoQ0dXemMxNnU1bThLX1VREgtlUG5XQkpuajdDMBIcChpDTS1jeS03WWplNENGZVFoZ3dvZEEwY01wUQ',
                       'choice_key': 'bts',
                       'created_at': datetime.datetime(2021, 1, 9, 1, 25, 55,
                                                       616000, tzinfo=pytz.utc),
                       'extra': {'match_key': 'bang vs bts'},
                       'ingested_at': datetime.datetime(2021, 1, 9, 1, 25, 54,
                                                        682000,
                                                        tzinfo=pytz.utc),
                       'program_id': '5ff90621ad5fa0db25cf0642',
                       'text': '1',
                       'version': '1.0.0',
                       'vote_type': 'vote',
                       'voted_at': datetime.datetime(2021, 1, 9, 1, 25, 53,
                                                     902000,
                                                     tzinfo=pytz.utc)}]}}

        DicttreeTool.keys2removed(data_in, ['_cache'])

        # def test_01(self):
    #     DicttreeTool.jpath2validated(
    #         {'a':{'b':None}},
    #         ['a','b']
    #     )
    #
    #     with self.assertRaises(Exception):
    #         DicttreeTool.jpath2validated(
    #             {'a': {'b': None}},
    #             ['a', 'c']
    #         )
